components:
  - name: ubuntu
    arg: UBUNTU_VERSION
    version: "20.04"
    arg_value: "focal-20241011"
    ubuntu_codename: "focal"
    build_date: "20241011"
format: "ubuntu20.4-focal-{build_date}"
requiresIsLatest: false
