components:
  - name: golang
    arg: GOLANG_VERSION
    version: "1.26.8"
  - name: python
    arg: PYTHON_VERSION
    version: "3.14"
  - name: golangci-lint
    arg: GOLANGCILINT_VERSION
    version: "2.12.2"
  - name: ruff
    arg: RUFF_VERSION
    version: "0.16.2"
format: "{golang}-python-{python}-golangci-lint-{golangci-lint}-ruff-{ruff}"
requiresIsLatest: true
