components:
  - name: golang
    arg: GOLANG_VERSION
    version: "1.26.8-bookworm"
    has_distro_suffix: true
  - name: golangci-lint
    arg: GOLANGCILINT_VERSION
    version: "2"
    arg_value: "2.12.2"
format: "{golang}-golangci-lint-{golangci-lint}"
requiresIsLatest: true
