FROM golang:1.17.4

RUN wget -O /usr/local/bin/nancy "https://github.com/sonatype-nexus-community/nancy/releases/download/v1.0.29/nancy-v1.0.29-linux-amd64" \
    && chmod 755 /usr/local/bin/nancy

CMD /bin/bash
