FROM golang:1.15

RUN wget -O /usr/local/bin/nancy "https://github.com/sonatype-nexus-community/nancy/releases/download/v1.0.17/nancy-v1.0.17-linux-amd64" \
    && chmod 755 /usr/local/bin/nancy

CMD /bin/bash
