components:
  - name: golang
    arg: GOLANG_VERSION
    version: "1.26.8"
    has_distro_suffix: false
  - name: docker
    arg: DOCKER_VERSION
    version: "28"
    arg_value: "28.5.2-dind"
  - name: python
    arg: PYTHON_VERSION
    version: "3.14"
format: "{golang}-python-{python}-dind-{docker}"
requiresIsLatest: true
