components:
  - name: golang
    arg: GOLANG_VERSION
    version: "1.26.8-bookworm"
    has_distro_suffix: true
  - name: golangci-lint
    arg: GOLANGCILINT_VERSION
    version: "2"
    arg_value: "2.12.2"
  - name: node
    arg: NODEJS_VERSION
    version: "24"
    arg_value: "24.19.0"
format: "{golang}-golangci-lint-{golangci-lint}-node-{node}"
requiresIsLatest: true
